# Generated by Django 5.0.7 on 2024-07-10 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("followSupportTest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.TextField()),
                ("author", models.CharField(max_length=100)),
                ("date", models.DateTimeField()),
                ("num_likes", models.IntegerField()),
                ("emotion", models.CharField(max_length=100)),
                ("object", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="VideoStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_id", models.CharField(max_length=50)),
                ("upload_date", models.DateTimeField()),
                ("date", models.DateField()),
                ("view_count", models.IntegerField()),
                ("like_count", models.IntegerField()),
                ("comment_count", models.IntegerField()),
                ("subscriber_count", models.IntegerField()),
                ("channel_id", models.CharField(max_length=50)),
                ("channel_title", models.CharField(max_length=100)),
                ("channel_description", models.TextField(null=True)),
                ("topic_categories", models.TextField(null=True)),
                ("title", models.CharField(max_length=200, null=True)),
                ("description", models.TextField(null=True)),
                ("tags", models.TextField(null=True)),
                ("thumbnails", models.CharField(max_length=255)),
            ],
            options={
                "unique_together": {("video_id", "date")},
            },
        ),
        migrations.DeleteModel(
            name="MyModel",
        ),
        migrations.AddField(
            model_name="comment",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="followSupportTest.videostat",
            ),
        ),
    ]
