# Generated by Django 5.0.7 on 2024-08-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("followSupportTest", "0002_comment_videostat_delete_mymodel_comment_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleTrend",
            fields=[
                ("trend_num", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("오킹TV", models.IntegerField(blank=True, null=True)),
                ("동수칸TV", models.IntegerField(blank=True, null=True)),
                ("뻑가PPKKa", models.IntegerField(blank=True, null=True)),
                ("깡스타일리스트", models.IntegerField(blank=True, null=True)),
                ("때잉", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "googleTrend",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RelatedKeyword",
            fields=[
                ("keyword_num", models.AutoField(primary_key=True, serialize=False)),
                ("channel_title", models.CharField(max_length=100)),
                ("keyword", models.CharField(max_length=100)),
                ("indicator", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "relatedKeyword",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="YoutuberStat",
            fields=[
                ("youtuber_num", models.AutoField(primary_key=True, serialize=False)),
                ("channel_title", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("followSupport", models.FloatField()),
                ("followScore", models.FloatField()),
                ("emotion", models.CharField(blank=True, max_length=100, null=True)),
                ("avg_view_count", models.IntegerField(blank=True, null=True)),
                ("avg_comment_count", models.IntegerField(blank=True, null=True)),
                ("avg_subscriber_count", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "YoutuberStat",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ImageUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/")),
            ],
        ),
        migrations.AlterModelOptions(
            name="videostat",
            options={"managed": False},
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
